version: 2.1

orbs:
  ivy-circleci-orb: nxtlytics/ivy-circleci-orb@0.0.5

workflows:
  version: 2
  build:
    jobs:
      - ivy-circleci-orb/build_docker:
          name: base
          working_directory: base/
          container_name: base
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: datadog-agent
          requires:
            - base
          working_directory: datadog-agent/
          container_name: datadog-agent
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: nodejs
          requires:
            - base
          working_directory: nodejs/
          container_name: nodejs
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: python37
          requires:
            - base
          working_directory: python37/
          container_name: python37
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: python38
          requires:
            - base
          working_directory: python38/
          container_name: python38
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: python39
          requires:
            - base
          working_directory: python39/
          container_name: python39
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: ruby
          requires:
            - base
          working_directory: ruby/
          container_name: ruby
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: ruby-jemalloc
          requires:
            - base
          working_directory: ruby-jemalloc/
          container_name: ruby-jemalloc
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: ruby-truffle
          requires:
            - base
          working_directory: ruby-truffle/
          container_name: ruby-truffle
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jdk
          requires:
            - base
          working_directory: jdk/
          container_name: jdk
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jupyterhub-singleuser-base
          requires:
            - python38
          working_directory: jupyterhub-singleuser-base/
          container_name: jupyterhub-singleuser-base
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-jdk
          requires:
            - jdk
          working_directory: jenkins/jdk/
          container_name: jenkins-jdk
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-nodejs
          requires:
            - jenkins-jdk
          working_directory: jenkins/nodejs/
          container_name: jenkins-nodejs
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-python37
          requires:
            - jenkins-jdk
          working_directory: jenkins/python37/
          container_name: jenkins-python37
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-python38
          requires:
            - jenkins-jdk
          working_directory: jenkins/python38/
          container_name: jenkins-python38
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-python39
          requires:
            - jenkins-jdk
          working_directory: jenkins/python39/
          container_name: jenkins-python39
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-ruby
          requires:
            - jenkins-jdk
          working_directory: jenkins/ruby/
          container_name: jenkins-ruby
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-ruby-jemalloc
          requires:
            - jenkins-jdk
          working_directory: jenkins/ruby-jemalloc/
          container_name: jenkins-ruby-jemalloc
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - ivy-circleci-orb/build_docker:
          name: jenkins-ruby-truffle
          requires:
            - jenkins-jdk
          working_directory: jenkins/ruby-truffle/
          container_name: jenkins-ruby-truffle
          simple_docker_tag: true
          context: ivy
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
