name: Build jenkins-agent-containers

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # required to use OIDC authentication
  contents: read

jobs:
  jdk:
    name: Build jdk container and push to public ECR
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: jdk/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-jdk:${{ steps.get-version.outputs.VERSION }}
  nodejs:
    name: Build nodejs container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: nodejs/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-nodejs:${{ steps.get-version.outputs.VERSION }}
  python37:
    name: Build python 3.7 container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: python37/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-python37:${{ steps.get-version.outputs.VERSION }}
  python38:
    name: Build python 3.8 container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: python38/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-python38:${{ steps.get-version.outputs.VERSION }}
  python39:
    name: Build python 3.9 container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: python39/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-python39:${{ steps.get-version.outputs.VERSION }}
  python310:
    name: Build python 3.10 container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: python310/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-python310:${{ steps.get-version.outputs.VERSION }}
  ruby:
    name: Build ruby container and push to public ECR
    runs-on: ubuntu-latest
    needs: jdk
    steps:
      - name: Get the version
        id: get-version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 900 # Member must have value greater than or equal to 900
          aws-region: us-east-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ruby/
          tags: |
            public.ecr.aws/e5r9m0c5/jenkins-ruby:${{ steps.get-version.outputs.VERSION }}
